{% set name = "exchange-calendars" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: exchange_calendars-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exchange_calendars-{{ version }}.tar.gz
  md5: cde61c2c11e5167d2faa48defdb364f4

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  include_recipe: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - exchange_calendars

about:
  home: https://github.com/gerrymanoim/exchange_calendars
  license: BSD License
